name: Update Root Path

on:
  push:
    branches:
      - main

jobs:
  update-root-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

      - name: Modify test test/overwrite.file.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          branch: main
          path: nest-cli.json
          body: "root: ${{ steps.abc.outputs.modified }}"
          overwrite: "true"

      # - name: List Modified Files
      #   run: |
      #     modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
      #     echo "Modified Files:"
      #     echo "$modified_files"

      # - name: Determine modified module
      #   id: detect-modified-module
      #   run: |
      #     if git diff --name-only HEAD^..HEAD --relative=apps/ | grep -q '^camped/'; then
      #       echo "::set-output name=module::camped"
      #     elif git diff --name-only HEAD^..HEAD --relative=apps/ | grep -q '^clock-gain/'; then
      #       echo "::set-output name=module::clock-gain"
      #     else
      #       echo "::set-output name=module::none"
      # fi
      # - name: Give write permission to nest-cli.json
      #   run: chmod +w nest-cli.json

      # - name: Update nest-cli.json root path
      #   run: |
      #     module=${{ steps.detect-modified-module.outputs.module }}
      #     echo "Detected module: $module"
      #     jq '.root = "apps/" + env.module' nest-cli.json > nest-cli-updated.json
      #     cat nest-cli-updated.json  # Print the updated JSON
      #     mv nest-cli-updated.json nest-cli.json

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to AWS ECR
      #   if: ${{ steps.detect-modified-module.outputs.module != 'none' }}
      #   run: |
      #     echo $(aws ecr get-login-password --region $AWS_REGION) | docker login --username AWS --password-stdin 203320314678.dkr.ecr.$AWS_REGION.amazonaws.com

      # - name: Build Docker image
      #   if: ${{ steps.detect-modified-module.outputs.module != 'none' }}
      #   run: |
      #     docker build -t ${{ steps.detect-modified-module.outputs.module }} .

      # Continue with the rest of your steps for building and deploying...
